### ISSUE TITLE
Different Versions?

### ISSUE THREAD

**Issue by paul-eeoc** [crazy-max/github-desktop-portable#1]
Chocolate-Covered Yaks (3.3.4.0) is the latest version of Github Desktop.    But the portable one is a beta version -- is it possible to choose between the general release and the beta release?

**Comment by crazy-max** [comment]
Hi @paul-eeoc,

Yes indeed, i'm using the beta Github Desktop. Unfortunately, the current stable is not designed to be portable because it's a clickonce application (the beta is a nupkg app).
I will specify this in the README but any suggestion is welcomed!

**Comment by paul-eeoc** [comment]
I thought as much.   The one feature that I miss is the 'open in git shell' or cmd that is in Chocolate-Covered Yaks.  This feature is not yet in the beta, but it is in the works as a feature:
https://github.com/desktop/desktop/milestone/7 https://github.com/desktop/desktop/issues/888

**Comment by paul-eeoc** [comment]
For the public, to ensure everyone understands:  the current (non-beta) release Chocolate-Covered Yaks (3.3.4.0)  to the public is a [clickonce](https://en.wikipedia.org/wiki/ClickOnce) application.  The beta release, currently 0.6.0, is a brand new overhaul, redesigned [electron](https://electron.atom.io/) (not clickonce) application.

**Comment by crazy-max** [comment]
@paul-eeoc Yes i will add this to the README. Thanks for your contrib!
